# Scheduler settings
queue: normal
ncpus: 16
walltime: 1:00:00
mem: 64GB
jobname: cable_example

# Model settings
model: cable
exe: /home/189/sb8430/cable/trunk/offline/cable-mpi # cable trunk (last changed revision: 9469):
input:
    - /home/189/sb8430/cable_inputs/landsea-access-esm.nc
    - /home/189/sb8430/cable/CABLE-AUX/core/biogeophys/def_veg_params_zr_clitt_albedo_fix.txt
    - /home/189/sb8430/cable/CABLE-AUX/core/biogeophys/def_soil_params.txt
    - /g/data/tm70/ccc561/CABLE/CABLE-as-ACCESS_Yingping/input/gridinfo-access-esm.nc
    - /g/data/tm70/ccc561/CABLE/CABLE-as-ACCESS_Yingping/cruncep10

# Disable collation
collate: False

# The walltime time used for one run ~ 3 minutes
runspersub: 10

# Specify restart directory (warm start). Should contain:
# - cable.res.yaml
# - restart.nc (CABLE restart file)
restart: /home/189/sb8430/cable_restart_1903

