# Scheduler settings
queue: normal
ncpus: 16
walltime: 1:00:00
mem: 64GB
jobname: cable_example

# Model settings
model: cable
exe: /home/189/sb8430/cable/trunk/offline/cable-mpi # cable trunk (last changed revision: 9469):
input:
    - /g/data/tm70/sb8430/cable/MetForcing/crujra_access/LWdown
    - /g/data/tm70/sb8430/cable/MetForcing/crujra_access/PSurf
    - /g/data/tm70/sb8430/cable/MetForcing/crujra_access/Qair
    - /g/data/tm70/sb8430/cable/MetForcing/crujra_access/Rainf
    - /g/data/tm70/sb8430/cable/MetForcing/crujra_access/Snowf
    - /g/data/tm70/sb8430/cable/MetForcing/crujra_access/SWdown
    - /g/data/tm70/sb8430/cable/MetForcing/crujra_access/Tair
    - /g/data/tm70/sb8430/cable/MetForcing/crujra_access/Wind
    - /g/data/tm70/sb8430/cable/MetForcing/crujra_access/crujra_access_landmask.nc
    - /g/data/tm70/sb8430/cable/MetForcing/crujra_access/crujra_access_gridinfo.nc
    - /home/189/sb8430/cable/CABLE-AUX/core/biogeophys/def_veg_params_zr_clitt_albedo_fix.txt
    - /home/189/sb8430/cable/CABLE-AUX/core/biogeophys/def_soil_params.txt

# Disable collation
collate: False

# The walltime time used for one run ~ 3 minutes
runspersub: 10

